import { NextResponse } from 'next/server';

export async function GET() {
  const agents = [
    { id: 1, name: 'Supabase Architect', squad: 'Backend', status: 'running', progress: 85, task: 'Database schema optimization' },
    { id: 2, name: 'Auth Specialist', squad: 'Backend', status: 'running', progress: 92, task: 'OAuth flow fixes' },
    { id: 3, name: 'API Engineer', squad: 'Backend', status: 'running', progress: 78, task: 'Rate limiting implementation' },
    { id: 4, name: 'Security Expert', squad: 'Backend', status: 'running', progress: 88, task: 'RLS policies' },
    { id: 5, name: 'Performance Engineer', squad: 'Backend', status: 'running', progress: 81, task: 'Query optimization' },
    { id: 6, name: 'Migration Specialist', squad: 'Backend', status: 'running', progress: 95, task: 'Schema migrations' },
    { id: 7, name: 'Realtime Specialist', squad: 'Backend', status: 'running', progress: 73, task: 'Live subscriptions' },
    { id: 8, name: 'Storage Engineer', squad: 'Backend', status: 'running', progress: 89, task: 'File upload system' },
    { id: 9, name: 'Backup Specialist', squad: 'Backend', status: 'running', progress: 67, task: 'Backup automation' },
    { id: 10, name: 'Monitoring Expert', squad: 'Backend', status: 'running', progress: 71, task: 'Health checks' },
    { id: 11, name: 'Types Specialist', squad: 'Backend', status: 'completed', progress: 100, task: 'TypeScript types' },
    { id: 12, name: 'Webhooks Engineer', squad: 'Backend', status: 'running', progress: 82, task: 'Webhook handlers' },
    { id: 13, name: 'Multi-tenant Architect', squad: 'Backend', status: 'running', progress: 76, task: 'Tenant isolation' },
    { id: 14, name: 'Testing Specialist', squad: 'Backend', status: 'running', progress: 69, task: 'Test suite' },
    { id: 15, name: 'Config Manager', squad: 'Backend', status: 'running', progress: 91, task: 'Environment config' },
    { id: 16, name: 'React Developer', squad: 'Frontend', status: 'running', progress: 87, task: 'Component optimization' },
    { id: 17, name: 'Next.js Specialist', squad: 'Frontend', status: 'running', progress: 93, task: 'App Router setup' },
    { id: 18, name: 'TypeScript Expert', squad: 'Frontend', status: 'running', progress: 79, task: 'Type safety' },
    { id: 19, name: 'State Manager', squad: 'Frontend', status: 'running', progress: 84, task: 'Zustand stores' },
    { id: 20, name: 'Hooks Specialist', squad: 'Frontend', status: 'running', progress: 77, task: 'Custom hooks' },
    { id: 21, name: 'Forms Expert', squad: 'Frontend', status: 'running', progress: 88, task: 'Form validation' },
    { id: 22, name: 'Data Fetching', squad: 'Frontend', status: 'running', progress: 74, task: 'SWR integration' },
    { id: 23, name: 'Routing Specialist', squad: 'Frontend', status: 'running', progress: 86, task: 'Route optimization' },
    { id: 24, name: 'Context Manager', squad: 'Frontend', status: 'running', progress: 68, task: 'React Context' },
    { id: 25, name: 'Animation Expert', squad: 'Frontend', status: 'running', progress: 90, task: 'Framer Motion' },
    { id: 26, name: 'Icon Specialist', squad: 'Frontend', status: 'running', progress: 72, task: 'Icon system' },
    { id: 27, name: 'Utilities Developer', squad: 'Frontend', status: 'running', progress: 83, task: 'Helper functions' },
    { id: 28, name: 'Testing Engineer', squad: 'Frontend', status: 'running', progress: 65, task: 'Component tests' },
    { id: 29, name: 'SSR Specialist', squad: 'Frontend', status: 'running', progress: 80, task: 'Server Components' },
    { id: 30, name: 'PWA Developer', squad: 'Frontend', status: 'running', progress: 75, task: 'Service workers' },
    { id: 31, name: 'SEO Specialist', squad: 'Frontend', status: 'running', progress: 70, task: 'Meta tags' },
    { id: 32, name: 'i18n Engineer', squad: 'Frontend', status: 'running', progress: 85, task: 'Translations' },
    { id: 33, name: 'Accessibility Expert', squad: 'Frontend', status: 'running', progress: 78, task: 'a11y compliance' },
    { id: 34, name: 'Performance Engineer', squad: 'Frontend', status: 'running', progress: 92, task: 'Code splitting' },
    { id: 35, name: 'Error Handler', squad: 'Frontend', status: 'running', progress: 81, task: 'Error boundaries' },
    { id: 36, name: 'UI Designer', squad: 'UI/UX', status: 'running', progress: 89, task: 'Design system' },
    { id: 37, name: 'Tailwind Expert', squad: 'UI/UX', status: 'running', progress: 94, task: 'CSS config' },
    { id: 38, name: 'Component Designer', squad: 'UI/UX', status: 'running', progress: 87, task: 'UI library' },
    { id: 39, name: 'Responsive Designer', squad: 'UI/UX', status: 'running', progress: 82, task: 'Mobile-first' },
    { id: 40, name: 'Dark Mode Expert', squad: 'UI/UX', status: 'running', progress: 91, task: 'Theme system' },
    { id: 41, name: 'Layout Designer', squad: 'UI/UX', status: 'running', progress: 76, task: 'Grid system' },
    { id: 42, name: 'Micro-interactions', squad: 'UI/UX', status: 'running', progress: 88, task: 'Animations' },
    { id: 43, name: 'Navigation Designer', squad: 'UI/UX', status: 'running', progress: 73, task: 'Nav patterns' },
    { id: 44, name: 'Feedback Designer', squad: 'UI/UX', status: 'running', progress: 86, task: 'Toast system' },
    { id: 45, name: 'Loading States', squad: 'UI/UX', status: 'running', progress: 79, task: 'Skeletons' },
    { id: 46, name: 'Typography Expert', squad: 'UI/UX', status: 'running', progress: 84, task: 'Font system' },
    { id: 47, name: 'Spacing Designer', squad: 'UI/UX', status: 'running', progress: 71, task: 'Spacing scale' },
    { id: 48, name: 'Color Specialist', squad: 'UI/UX', status: 'running', progress: 90, task: 'Color palette' },
    { id: 49, name: 'Consistency Manager', squad: 'UI/UX', status: 'running', progress: 77, task: 'Design tokens' },
    { id: 50, name: 'Mobile UX', squad: 'UI/UX', status: 'running', progress: 83, task: 'Touch targets' },
    { id: 51, name: 'Auth Flow', squad: 'Auth', status: 'running', progress: 96, task: 'Login flow' },
    { id: 52, name: 'OAuth Expert', squad: 'Auth', status: 'running', progress: 89, task: 'Social auth' },
    { id: 53, name: 'Phone Auth', squad: 'Auth', status: 'running', progress: 74, task: 'OTP system' },
    { id: 54, name: 'Security Manager', squad: 'Auth', status: 'running', progress: 92, task: 'Password policy' },
    { id: 55, name: 'Middleware Engineer', squad: 'Auth', status: 'running', progress: 85, task: 'Route guards' },
    { id: 56, name: 'Auth Context', squad: 'Auth', status: 'running', progress: 78, task: 'Auth provider' },
    { id: 57, name: 'Auth UI', squad: 'Auth', status: 'running', progress: 88, task: 'Login forms' },
    { id: 58, name: 'Auth Errors', squad: 'Auth', status: 'running', progress: 81, task: 'Error handling' },
    { id: 59, name: 'Auth Testing', squad: 'Auth', status: 'running', progress: 67, task: 'Auth tests' },
    { id: 60, name: 'Remember Me', squad: 'Auth', status: 'running', progress: 72, task: 'Persistent login' },
    { id: 61, name: 'TypeScript Bug Hunter', squad: 'Bug Fix', status: 'running', progress: 87, task: 'Type fixes' },
    { id: 62, name: 'Runtime Bug Fixer', squad: 'Bug Fix', status: 'running', progress: 91, task: 'Runtime errors' },
    { id: 63, name: 'Import/Export Fixer', squad: 'Bug Fix', status: 'running', progress: 76, task: 'Module fixes' },
    { id: 64, name: 'Build Error Fixer', squad: 'Bug Fix', status: 'running', progress: 94, task: 'Build config' },
    { id: 65, name: 'API Bug Fixer', squad: 'Bug Fix', status: 'running', progress: 83, task: 'API errors' },
    { id: 66, name: 'State Bug Fixer', squad: 'Bug Fix', status: 'running', progress: 79, task: 'State issues' },
    { id: 67, name: 'UI Bug Fixer', squad: 'Bug Fix', status: 'running', progress: 86, task: 'UI bugs' },
    { id: 68, name: 'Hooks Bug Fixer', squad: 'Bug Fix', status: 'running', progress: 80, task: 'Hook fixes' },
    { id: 69, name: 'Memory Leak Fixer', squad: 'Bug Fix', status: 'running', progress: 75, task: 'Memory issues' },
    { id: 70, name: 'Async Bug Fixer', squad: 'Bug Fix', status: 'running', progress: 89, task: 'Async fixes' },
    { id: 71, name: 'CSS Bug Fixer', squad: 'Bug Fix', status: 'running', progress: 82, task: 'Styling fixes' },
    { id: 72, name: 'Form Bug Fixer', squad: 'Bug Fix', status: 'running', progress: 77, task: 'Form fixes' },
    { id: 73, name: 'Auth Bug Fixer', squad: 'Bug Fix', status: 'running', progress: 90, task: 'Auth bugs' },
    { id: 74, name: 'Edge Case Fixer', squad: 'Bug Fix', status: 'running', progress: 68, task: 'Edge cases' },
    { id: 75, name: 'Console Error Fixer', squad: 'Bug Fix', status: 'running', progress: 93, task: 'Console cleanup' },
    { id: 76, name: 'Grading Feature', squad: 'Features', status: 'running', progress: 95, task: 'AI grading' },
    { id: 77, name: 'Flashcards Feature', squad: 'Features', status: 'running', progress: 88, task: 'SM-2 algorithm' },
    { id: 78, name: 'Documents Feature', squad: 'Features', status: 'running', progress: 84, task: 'Block editor' },
    { id: 79, name: 'Chat Feature', squad: 'Features', status: 'running', progress: 79, task: 'AI tutor' },
    { id: 80, name: 'Library Feature', squad: 'Features', status: 'running', progress: 73, task: 'Resource library' },
    { id: 81, name: 'Dashboard Feature', squad: 'Features', status: 'running', progress: 91, task: 'Analytics' },
    { id: 82, name: 'Settings Feature', squad: 'Features', status: 'running', progress: 86, task: 'User prefs' },
    { id: 83, name: 'Quiz Feature', squad: 'Features', status: 'running', progress: 81, task: 'Quiz system' },
    { id: 84, name: 'Progress Feature', squad: 'Features', status: 'running', progress: 85, task: 'Tracking' },
    { id: 85, name: 'Collaboration', squad: 'Features', status: 'running', progress: 70, task: 'Sharing' },
    { id: 86, name: 'Notifications', squad: 'Features', status: 'running', progress: 92, task: 'Push notifications' },
    { id: 87, name: 'Search Feature', squad: 'Features', status: 'running', progress: 78, task: 'Full-text search' },
    { id: 88, name: 'Export Feature', squad: 'Features', status: 'running', progress: 83, task: 'PDF export' },
    { id: 89, name: 'Import Feature', squad: 'Features', status: 'running', progress: 69, task: 'Data import' },
    { id: 90, name: 'Gamification', squad: 'Features', status: 'running', progress: 87, task: 'Badges/points' },
    { id: 91, name: 'Vercel Deploy', squad: 'Deploy', status: 'running', progress: 98, task: 'Production deploy' },
    { id: 92, name: 'Vercel Config', squad: 'Deploy', status: 'running', progress: 95, task: 'Build config' },
    { id: 93, name: 'Vercel Env', squad: 'Deploy', status: 'running', progress: 97, task: 'Environment vars' },
    { id: 94, name: 'Vercel Build', squad: 'Deploy', status: 'running', progress: 94, task: 'Build optimization' },
    { id: 95, name: 'Vercel Functions', squad: 'Deploy', status: 'running', progress: 89, task: 'Edge functions' },
    { id: 96, name: 'Vercel Edge', squad: 'Deploy', status: 'running', progress: 91, task: 'Edge config' },
    { id: 97, name: 'Vercel CI/CD', squad: 'Deploy', status: 'running', progress: 93, task: 'GitHub Actions' },
    { id: 98, name: 'Vercel Monitoring', squad: 'Deploy', status: 'running', progress: 88, task: 'Analytics' },
    { id: 99, name: 'Vercel Domains', squad: 'Deploy', status: 'running', progress: 90, task: 'Custom domain' },
    { id: 100, name: 'Vercel Integration', squad: 'Deploy', status: 'running', progress: 96, task: 'Full integration' },
  ];

  return NextResponse.json({ agents, total: agents.length, running: agents.filter(a => a.status === 'running').length, completed: agents.filter(a => a.status === 'completed').length });
}
